Samanvitha
XSiling/CSE210-Project pull request #94
Opened 2023-12-07 20:39 UTC by Samanvitha-Sateesha

2023-12-09 04:02 UTC, DevChuriwala requested changes
lgtm, tried it out on local... seems to work fine!

there are a lot of unnecessary comments in the code - maybe you should take them out before merging into main...

2023-12-11 04:48 UTC, XSiling approved these changes

2023-12-11 04:54 UTC, DevChuriwala approved these changes
lgtm!

2023-12-11 05:10 UTC, Niko-Yuan approved these changes

2023-12-11 05:11 UTC, merged